# 개발용 # 도커 컴포즈로 실행
# docker-compose -f dev-stack.yml up

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_ENCODING: UTF8
      POSTGRES_COLLATE: en_US.utf8
      POSTGRES_CTYPE: en_US.utf8
      POSTGRES_INITDB_ARGS: "--locale=en_US.utf8 --encoding=UTF8"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    user: "${UID:-1000}:${GID:-1000}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    networks:
      default:
        ipv4_address: 172.23.0.6

  adminer:
    image: adminer
    restart: always
    ports:
      - "8790:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:
        ipv4_address: 172.23.0.8

  redis:
    image: redis
    expose:
      - 6379
    command:
      - redis-server
    networks:
      default:
        ipv4_address: 172.23.0.79
