definitions:
  models.Post:
    properties:
      createdAt:
        type: string
      deleted_at:
        type: string
      id:
        example: "0"
        type: string
      title:
        type: string
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deleted_at:
        type: string
      id:
        example: "0"
        type: string
      name:
        type: string
      posts:
        items:
          $ref: '#/definitions/models.Post'
        type: array
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: Get a user
  version: "3.1"
paths:
  /users/{id}:
    get:
      description: Get a user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get a user
      tags:
      - users
produces:
- application/json
swagger: "2.0"
